In [139]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score as acc,confusion_matrix,roc_auc_score,roc_curve

In [26]:
data=load_iris()
features=data['target_names']

In [144]:
X=pd.DataFrame(data['data'],columns=data['feature_names'])
Y=pd.DataFrame(data['target'],columns=['target'])
Y['target'] = Y['target'].apply(lambda x: data['target_names'][x])
y=Y['target']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object

In [145]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=97)

In [146]:
LogReg=LogisticRegression(random_state=30,max_iter=300)
RandomForest=RandomForestClassifier(random_state=12,n_estimators=400)
gaussian=GaussianNB()
decisionTree=DecisionTreeClassifier(random_state=9,criterion='log_loss')

In [147]:
LogReg.fit(X_train,y_train)

LogisticRegression(max_iter=300, random_state=30)

In [148]:
RandomForest.fit(X_train,y_train)

RandomForestClassifier(n_estimators=400, random_state=12)

In [149]:
gaussian.fit(X_train,y_train)

GaussianNB()

In [150]:
decisionTree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='log_loss', random_state=9)

In [151]:
LogReg_pred=LogReg.predict(X_test)
RandomForest_pred=RandomForest.predict(X_test)
gaussian_pred=gaussian.predict(X_test)
decisionTree_pred=decisionTree.predict(X_test)

In [152]:
LogReg_acc=acc(y_test,LogReg_pred)
RandomForest_acc=acc(y_test,RandomForest_pred)
gaussian_acc=acc(y_test,gaussian_pred)
decisionTree_acc=acc(y_test,decisionTree_pred)


In [153]:
print('The Accuracy of Logistic Regression:',LogReg_acc,'\nThe Accuracy of Random Forest Classifier:',RandomForest_acc,'\nThe Accuracy of Gaussian Naive bayes:',gaussian_acc,'\nThe Accuracy of Decision Tree Classifier:',decisionTree_acc)

The Accuracy of Logistic Regression: 0.9555555555555556 
The Accuracy of Random Forest Classifier: 0.9333333333333333 
The Accuracy of Gaussian Naive bayes: 0.9111111111111111 
The Accuracy of Decision Tree Classifier: 0.8888888888888888


In [155]:
print('The Confusion matrix of Logistic Regression:\n',confusion_matrix(y_test,LogReg_pred),'\nThe Confusion matrix of Random Forest Classifier:\n',confusion_matrix(y_test,RandomForest_pred),'\nThe Confusion matrix of Gaussian Naive bayes:\n',confusion_matrix(y_test,gaussian_pred),'\nThe Confusion matrix of Decision Tree Classifier:\n',confusion_matrix(y_test,decisionTree_pred))

The Confusion matrix of Logistic Regression:
 [[13  0  0]
 [ 0 14  2]
 [ 0  0 16]] 
The Confusion matrix of Random Forest Classifier:
 [[13  0  0]
 [ 0 13  3]
 [ 0  0 16]] 
The Confusion matrix of Gaussian Naive bayes:
 [[13  0  0]
 [ 0 12  4]
 [ 0  0 16]] 
The Confusion matrix of Decision Tree Classifier:
 [[13  0  0]
 [ 0 11  5]
 [ 0  0 16]]
